name: mypy-test

on:
  push:
    paths:
      - 'app/*.py'

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          architecture: x64
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install mypy
        run: pip install mypy
      - name: Check Folders
        run: ls
      - name: Run mypy
        run: mypy --ignore-missing-imports *.py
